server:
  port: 8080

spring:
  datasource:
    password: 78647Sun&Bob
    url: jdbc:mysql://bobking.icu:3306/mall?useUnicode=true&characterEncoding=utf-8
    username: root
  redis:
    host: localhost
    database: 0
    port: 6379
    password: # Redis服务器连接密码（默认为空）
    jedis:
      pool:
        max-active: 8
        max-wait: -1ms
        max-idle: 8
        min-idle: 0
    lettuce:
      shutdown-timeout: 3000ms

mybatis:
  mapper-locations:
    - classpath:mapper/*.xml
    - classpath*:bobking/**/mapper/*.xml

redis:
  key:
    prefix:
      authCode: "portal:authCode:"
    expire:
      authCode: 120
