server:
  port: 8080

spring:
  datasource:
    password: bobking
    url: jdbc:mysql://bobking.icu:3306/mall?useUnicode=true&characterEncoding=utf-8
    username: root
  redis:
    host: bobking.icu
    database: 0   # 默认有16个database，从中选择一个
    port: 6379
    password: bobking # Redis服务器连接密码（默认为空）
    jedis:
      pool:
        max-active: 8
        max-wait: -1ms
        max-idle: 8
        min-idle: 0
    lettuce:
      shutdown-timeout: 3000ms
#  如果要连接远程的elastic需要配置以下的内容
  elasticsearch:
    rest:
      uris: ["bobking.icu:9200"]
  data:
    elasticsearch:
      repositories:
        enabled: true
      cluster-nodes: bobking.icu:9300 # es的连接地址及端口
      cluster-name: docker-cluster # es集群的名称

mybatis:
  mapper-locations:
    - classpath:mapper/*.xml
    - classpath*:bobking/**/mapper/*.xml

# 自定义redis key
redis:
  key:
    prefix:
      authCode: "portal:authCode:"
    expire:
      authCode: 120

# 自定义jwt key
jwt:
  tokenHeader: Authorization
  secret: bobking
  expiration: 604800  #7*24*60*60 token具有一周的过期时间
  tokenHead: Bearer